---
- name: Create VM
  hosts: localhost
  vars_files: 
    - credential.yml
  
  tasks:
  - name: Create Datacenter
    local_action:
      module: vmware_datacenter
      hostname: 172.180.0.200
      username: "{{ vc_user }}"
      password: "{{ vc_pwd }}"
      datacenter_name: Paris
      state: present
      validate_certs: no
