---
- name : Action VM
  hosts: localhost
  vars_files:
    - credential.yml

  tasks:
  - name: Create VM
    local_action:
      module: vmware_guest
      hostname: "{{ vc_ip }}"
      username: "{{ vc_user }}"
      password: "{{ vc_pwd }}"
      validate_certs: no
      name: "{{ vm_name }}"
      state: poweredoff
      folder: /
      datacenter: "{{ dc_name }}"
      guest_id: centos64Guest
      disk:
      - size_gb: "{{ disk_gb }}"
        type: thin
        datastore: "{{ vc_ds }}"
      networks:
      - name: VM Network
        type: dhcp
      hardware:
        memory_mb: "{{ memory_mb }}"
        num_cpus: "{{ cpu_num }}"
        scsi: paravirtual
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: False
    tags: vm
